### PR TITLE
Add documentation on jackson support in Mongo Adapter (still experimental)

### PR DESCRIPTION
**Pull request by asereda-gs**
Provide examples on how to use `JacksonCodecs` util class with `ObjectMapper` in mongo adapter

### CODE REVIEW

**Comment by asereda-gs** [comment]
@elucash do you have any comments on this (documentation) PR ?

**Comment by elucash** [comment]
This is good, thank you! I dunno, maybe I waited to some release to publish this, nowadays it requires some manual steps which I cannot get my hands to automate

**Comment by elucash** [comment]
so I'll release something this week and push generated documentation

**Comment by asereda-gs** [comment]
@elucash Are you looking for automated site push during maven release ? Or automatically upload static content when there is a change (to docs repository) ? 

Let me know how you want to automate it and I'll be happy to help.

**Pull request merged**
