### PR TITLE
Correct grammatical errors, typos, improve wording, etc

### PR DESCRIPTION
**Pull request by io7m**
Hello!

While the documentation for the `immutables` package is good, it seems rather apparent that it was not written by someone who has English as a first language. I've made a few passes over the text of the site in an attempt to improve the wording and grammar to make it somewhat more comprehensible.

A couple of issues:

* I don't have any way to preview the changes I've made, so it's possible that I've broken markdown somewhere and not realized it. This will obviously become apparent as soon as it is rendered as HTML, and I'll provide fixes for any damage.

* I couldn't fix the the last sentence of this paragraph from `immutable.md` (line ~663), because I just couldn't decipher it and didn't want to accidentally change the meaning:

> That said, restrictions still apply: Do not refer to lazy values from default or derived attributes.
Calling lazy attributes from derived or default attributes is _not always safe_. In effect,
it will result in the lazy value being eagerly computed. Moreover, if a lazy value
uses in computation one of those default or derived attributes, then it may found it uninitialized.

What exactly may be uninitialized?

I'd be happy to go through the immutables codebase and try to make similar improvements to the generated JavaDoc if the above changes are acceptable for the site.

### CODE REVIEW

**Comment by elucash** [comment]
This is a super awesome improvement! Thank you! Much appreciate! I'm finding mistakes almost each time I reread it, but this is huge!

**Comment by io7m** [comment]
> I'm finding mistakes almost each time I reread it

Yeah, I was concerned that I'd changed meanings in a few places. It likely needs adjustments.

**Comment by elucash** [comment]
Sorry, what I meant was that I was able to see very many mistakes of my own each time I read it (before your edits). And really glad that you did proofreading and the changes are great.

**Comment by io7m** [comment]
Hehe, no problem.

**Pull request merged**
