### PR TITLE
 Guide for using immutables with the V2 AWS SDK DynamoDB Enhanced Client

### PR DESCRIPTION
**Pull request by swar8080**
Updates the DynamoDB integration guide with a style for the V2 AWS SDK. This was originally discussed in https://github.com/immutables/immutables/issues/1478

I also moved the existing V1 SDK guide to a separate page that this new guide links to, since i'm assuming most people are looking for V2 info nowadays

**Reminder:** The guide's code won't work until 2.10 is released

### CODE REVIEW

**Comment by elucash** [comment]
Thank you! Sorry for merging only now, just got to release / maintenance stuff

**Comment by swar8080** [comment]
once this is published, I can suggest that its link is added to https://github.com/aws/aws-sdk-java-v2/tree/master/services-custom/dynamodb-enhanced#working-with-immutable-data-classes, which has an example for lombok users

**Comment by elucash** [comment]
apparently jekyll/ruby is not working (cannot install) on the laptop I have, so still figuring out how to publish docs, we've stopped using auto-publish by github years ago, will try to find some workaround / make it work. Will update when done, thank you!

**Comment by elucash** [comment]
At last I was able to re-publish site (using new laptop etc) https://immutables.github.io/dynamodb.html

**Pull request merged**
